### ISSUE TITLE
Txti is shutting down

### ISSUE THREAD

**Issue by TheRealOne78** [x3nu/CLItxties#4]
Hi, I just wanted to point out that in July 1st of 2023 (next month from this issue submission), the author(s) of txti.es will shut down the txti.es project.

> **Txti is shutting down.**
>Due to bad actors, txti will be shutting down permanently on July 1, 2023. Until that time, no new pages can be created. Please save any content you need and find another place for your content.
>Txti was created nine years ago with a simple and benevolant mission: to play a part in a more globally accessible internet. Since then, the whole world has changed. Now, there is less need for web pages that work on flip phones, and more need for trustworthiness and safety on the internet. As txti is not able to keep up with this need, it's time for it to step aside to ensure we're not causing harm.
>Thank you to everyone who used and loved txti. It was a fun and useful project that I simply wasn't able to maintain. There are many lessons learned here, but I'm grateful to have been a part of a special era of the internet's evolution.

\- http://txti.es/

**Comment by x3nu** [comment]
Thx for the info, haven't used it myself for a while
